### ISSUE TITLE
Please prioritize open source

### ISSUE THREAD

**Issue by jonpulsifer** [GoogleCloudPlatform/security-response-automation#188]
@tomscript / @peacockt (is this even tim?) what's the intention? should i be sending people here or not?

**Comment by peacockt** [comment]
Hey Jon! What makes you think we're dead?

**Comment by jonpulsifer** [comment]
![image](https://user-images.githubusercontent.com/5461940/83569425-775f5a00-a4f2-11ea-8f90-f6d8d8a034fe.png)

**Comment by peacockt** [comment]
Eh well that's fair. We've paused work here while getting our SCC Premium release out the door. Shoot me an email and we can discuss further.

**Comment by jonpulsifer** [comment]
what parts are we gonna make people pay for?
