### ISSUE TITLE
Add a full detailed example of config.yaml file

### ISSUE THREAD

**Issue by daniel-cit** [GoogleCloudPlatform/security-response-automation#189]
Add a full example of the `config.yaml` file with all the possible configurations set to be used as a starting point.

- Lines should be commented so that users can select what they want to use
- Fields that accept values from a set should have a comment listing the possible values and point to the documentation about them. 
- `dry_run` property initial value should de set to `true`
- `target` and `exclude` examples should also be provided

**Comment by daniel-cit** [comment]
[config.yaml.full-example.txt](https://github.com/GoogleCloudPlatform/security-response-automation/files/4815133/config.yaml.full-example.txt)


A full example of the config.yaml file. 
It must be rename to config.yaml  and place in folder `security-response-automation/cloudfunctions/router`.
Replace YOUR-ORGANIZATION-ID and YOUR-FOLDER-ID with the values used in the Terraform script.

**Comment by tomscript** [comment]
moved to https://github.com/GoogleCloudPlatform/security-response-automation/wiki/Sample-configuration
